midiIn: 'Gestionnaire IAC Bus 1'
midiOut: 'Gestionnaire IAC Bus 1'
port: 8080

pages:
  - sequence: '&'
    id: track 1

  - sequence: é
    id: track 2

  - sequence: '"'
    id: track 3

  - sequence: "'"
    id: track 4

  - sequence: (
    id: track 5

  - sequence: §
    id: track 6

  - sequence: è
    id: track 7

  - sequence: '!'
    id: track 8

  - sequence: ç
    id: macro 1

  - sequence: à
    id: macro 2

mapping:
  - sequence: q
    pages:
      - track 1
    type: analog
    increment: 1
    controller: 28
    channel: 0

  - sequence: w
    pages:
      - track 1
    type: analog
    increment: -1
    controller: 28
    channel: 0

  - sequence: q
    pages:
      - track 2
    type: analog
    increment: 1
    controller: 29
    channel: 0

  - sequence: w
    pages:
      - track 2
    type: analog
    increment: -1
    controller: 29
    channel: 0

  - sequence: q
    pages:
      - track 3
    type: analog
    increment: 1
    controller: 30
    channel: 0

  - sequence: w
    pages:
      - track 3
    type: analog
    increment: -1
    controller: 30
    channel: 0

  - sequence: q
    pages:
      - track 4
    type: analog
    increment: 1
    controller: 31
    channel: 0

  - sequence: w
    pages:
      - track 4
    type: analog
    increment: -1
    controller: 31
    channel: 0

  - sequence: q
    pages:
      - track 5
    type: analog
    increment: 1
    controller: 35
    channel: 0

  - sequence: w
    pages:
      - track 5
    type: analog
    increment: -1
    controller: 35
    channel: 0

  - sequence: q
    pages:
      - track 6
    type: analog
    increment: 1
    controller: 41
    channel: 0

  - sequence: w
    pages:
      - track 6
    type: analog
    increment: -1
    controller: 41
    channel: 0

  - sequence: q
    pages:
      - track 7
    type: analog
    increment: 1
    controller: 46
    channel: 0

  - sequence: w
    pages:
      - track 7
    type: analog
    increment: -1
    controller: 46
    channel: 0

  - sequence: q
    pages:
      - track 8
    type: analog
    increment: 1
    controller: 47
    channel: 0

  - sequence: w
    pages:
      - track 8
    type: analog
    increment: -1
    controller: 47
    channel: 0

  - sequence: q
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 48
    channel: 0

  - sequence: w
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 48
    channel: 0

  - sequence: s
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 49
    channel: 0

  - sequence: x
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 49
    channel: 0

  - sequence: d
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 50
    channel: 0

  - sequence: c
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 50
    channel: 0

  - sequence: f
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 51
    channel: 0

  - sequence: v
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 51
    channel: 0

  - sequence: g
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 52
    channel: 0

  - sequence: b
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 52
    channel: 0

  - sequence: h
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 53
    channel: 0

  - sequence: n
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 53
    channel: 0

  - sequence: j
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 54
    channel: 0

  - sequence: ','
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 54
    channel: 0

  - sequence: k
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 55
    channel: 0

  - sequence: ';'
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 55
    channel: 0

  - sequence: q
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 56
    channel: 0

  - sequence: w
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 56
    channel: 0

  - sequence: s
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 57
    channel: 0

  - sequence: x
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 57
    channel: 0

  - sequence: d
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 58
    channel: 0

  - sequence: c
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 58
    channel: 0

  - sequence: f
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 59
    channel: 0

  - sequence: v
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 59
    channel: 0

  - sequence: g
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 60
    channel: 0

  - sequence: b
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 60
    channel: 0

  - sequence: h
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 61
    channel: 0

  - sequence: n
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 61
    channel: 0

  - sequence: j
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 62
    channel: 0

  - sequence: ','
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 62
    channel: 0

  - sequence: k
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 63
    channel: 0

  - sequence: ';'
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 63
    channel: 0