midiIn: 'Gestionnaire IAC Bus 1'
midiOut: 'Gestionnaire IAC Bus 1'
port: 8080

pages:
  - sequence: '&'
    id: track 1

  - sequence: é
    id: track 2

  - sequence: '"'
    id: track 3

  - sequence: "'"
    id: track 4

  - sequence: (
    id: track 5

  - sequence: §
    id: track 6

  - sequence: è
    id: track 7

  - sequence: '!'
    id: track 8

  - sequence: ç
    id: macro 1

  - sequence: à
    id: macro 2

mapping:
  - sequence: q
    pages:
      - track 1
    type: analog
    increment: 1
    controller: 17
    channel: 0

  - sequence: w
    pages:
      - track 1
    type: analog
    increment: -1
    controller: 17
    channel: 0

  - sequence: q
    pages:
      - track 2
    type: analog
    increment: 1
    controller: 18
    channel: 0

  - sequence: w
    pages:
      - track 2
    type: analog
    increment: -1
    controller: 18
    channel: 0

  - sequence: q
    pages:
      - track 3
    type: analog
    increment: 1
    controller: 19
    channel: 0

  - sequence: w
    pages:
      - track 3
    type: analog
    increment: -1
    controller: 19
    channel: 0

  - sequence: q
    pages:
      - track 4
    type: analog
    increment: 1
    controller: 20
    channel: 0

  - sequence: w
    pages:
      - track 4
    type: analog
    increment: -1
    controller: 20
    channel: 0

  - sequence: q
    pages:
      - track 5
    type: analog
    increment: 1
    controller: 21
    channel: 0

  - sequence: w
    pages:
      - track 5
    type: analog
    increment: -1
    controller: 21
    channel: 0

  - sequence: q
    pages:
      - track 6
    type: analog
    increment: 1
    controller: 22
    channel: 0

  - sequence: w
    pages:
      - track 6
    type: analog
    increment: -1
    controller: 22
    channel: 0

  - sequence: q
    pages:
      - track 7
    type: analog
    increment: 1
    controller: 23
    channel: 0

  - sequence: w
    pages:
      - track 7
    type: analog
    increment: -1
    controller: 23
    channel: 0

  - sequence: q
    pages:
      - track 8
    type: analog
    increment: 1
    controller: 24
    channel: 0

  - sequence: w
    pages:
      - track 8
    type: analog
    increment: -1
    controller: 24
    channel: 0

  - sequence: q
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 1
    channel: 0

  - sequence: w
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 1
    channel: 0

  - sequence: s
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 2
    channel: 0

  - sequence: x
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 2
    channel: 0

  - sequence: d
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 3
    channel: 0

  - sequence: c
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 3
    channel: 0

  - sequence: f
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 4
    channel: 0

  - sequence: v
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 4
    channel: 0

  - sequence: g
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 5
    channel: 0

  - sequence: b
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 5
    channel: 0

  - sequence: h
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 6
    channel: 0

  - sequence: n
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 6
    channel: 0

  - sequence: j
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 7
    channel: 0

  - sequence: ','
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 7
    channel: 0

  - sequence: k
    pages:
      - macro 1
    type: analog
    increment: 1
    controller: 8
    channel: 0

  - sequence: ';'
    pages:
      - macro 1
    type: analog
    increment: -1
    controller: 8
    channel: 0

  - sequence: q
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 9
    channel: 0

  - sequence: w
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 9
    channel: 0

  - sequence: s
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 10
    channel: 0

  - sequence: x
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 10
    channel: 0

  - sequence: d
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 11
    channel: 0

  - sequence: c
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 11
    channel: 0

  - sequence: f
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 12
    channel: 0

  - sequence: v
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 12
    channel: 0

  - sequence: g
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 13
    channel: 0

  - sequence: b
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 13
    channel: 0

  - sequence: h
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 14
    channel: 0

  - sequence: n
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 14
    channel: 0

  - sequence: j
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 15
    channel: 0

  - sequence: ','
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 15
    channel: 0

  - sequence: k
    pages:
      - macro 2
    type: analog
    increment: 1
    controller: 16
    channel: 0

  - sequence: ';'
    pages:
      - macro 2
    type: analog
    increment: -1
    controller: 16
    channel: 0