midiIn: 'Gestionnaire IAC Bus 1'
midiOut: 'Gestionnaire IAC Bus 1'
port: 8080

pages:
  - sequence: '&'
    id: track 1

  - sequence: é
    id: track 2

  - sequence: '"'
    id: track 3

  - sequence: "'"
    id: track 4

  - sequence: (
    id: track 5

  - sequence: §
    id: track 6

  - sequence: è
    id: track 7

  - sequence: '!'
    id: track 8

mapping:
  - sequence: q
    pages:
      - track 1
    type: analog
    increment: 1
    controller: 28
    channel: 0

  - sequence: w
    pages:
      - track 1
    type: analog
    increment: -1
    controller: 28
    channel: 0

  - sequence: q
    pages:
      - track 2
    type: analog
    increment: 1
    controller: 29
    channel: 0

  - sequence: w
    pages:
      - track 2
    type: analog
    increment: -1
    controller: 29
    channel: 0

  - sequence: q
    pages:
      - track 3
    type: analog
    increment: 1
    controller: 30
    channel: 0

  - sequence: w
    pages:
      - track 3
    type: analog
    increment: -1
    controller: 30
    channel: 0

  - sequence: q
    pages:
      - track 4
    type: analog
    increment: 1
    controller: 31
    channel: 0

  - sequence: w
    pages:
      - track 4
    type: analog
    increment: -1
    controller: 31
    channel: 0

  - sequence: q
    pages:
      - track 5
    type: analog
    increment: 1
    controller: 35
    channel: 0

  - sequence: w
    pages:
      - track 5
    type: analog
    increment: -1
    controller: 35
    channel: 0

  - sequence: q
    pages:
      - track 6
    type: analog
    increment: 1
    controller: 41
    channel: 0

  - sequence: w
    pages:
      - track 6
    type: analog
    increment: -1
    controller: 41
    channel: 0

  - sequence: q
    pages:
      - track 7
    type: analog
    increment: 1
    controller: 46
    channel: 0

  - sequence: w
    pages:
      - track 7
    type: analog
    increment: -1
    controller: 46
    channel: 0

  - sequence: q
    pages:
      - track 8
    type: analog
    increment: 1
    controller: 47
    channel: 0

  - sequence: w
    pages:
      - track 8
    type: analog
    increment: -1
    controller: 47
    channel: 0