name: ableton live basic
port: 8080

midi:
  in: IAC AMC-IN
  out: IAC AMC-OUT
  socketIO: false

navigation:
  next: d
  previous: q
  scenes:
    - id: track 1
      sequence: '&'

    - id: encoder 1
      sequence: é

    - id: encoder 9
      sequence: '"'

global:
  mappings:
    - sequence: "p"
      label: play
      type: digital
      controller: 42
      channel: 0

    - sequence: " "
      label: stop
      type: digital
      controller: 41
      channel: 0

    - sequence: "\u001b[C"
      label: forward
      type: digital
      controller: 44
      channel: 0

    - sequence: "\u001b[D"
      label: backward
      type: digital
      controller: 43
      channel: 0

scenes:
  - id: track 1
    mappings:
      - sequence: z
        label: volume +
        type: analog
        increment: 1
        controller: 17
        channel: 0

      - sequence: s
        label: volume -
        type: analog
        increment: -1
        controller: 17
        channel: 0

  - id: track 2
    mappings:
      - sequence: z
        label: volume +
        type: analog
        increment: 1
        controller: 18
        channel: 0

      - sequence: s
        label: volume -
        type: analog
        increment: -1
        controller: 18
        channel: 0

  - id: track 3
    mappings:
      - sequence: z
        label: volume +
        type: analog
        increment: 1
        controller: 19
        channel: 0

      - sequence: s
        label: volume -
        type: analog
        increment: -1
        controller: 19
        channel: 0

  - id: track 4
    mappings:
      - sequence: z
        label: volume +
        type: analog
        increment: 1
        controller: 20
        channel: 0

      - sequence: s
        label: volume -
        type: analog
        increment: -1
        controller: 20
        channel: 0

  - id: track 5
    mappings:
      - sequence: z
        label: volume +
        type: analog
        increment: 1
        controller: 21
        channel: 0

      - sequence: s
        label: volume -
        type: analog
        increment: -1
        controller: 21
        channel: 0

  - id: track 6
    mappings:
      - sequence: z
        label: volume +
        type: analog
        increment: 1
        controller: 22
        channel: 0

      - sequence: s
        label: volume -
        type: analog
        increment: -1
        controller: 22
        channel: 0

  - id: track 7
    mappings:
      - sequence: z
        label: volume +
        type: analog
        increment: 1
        controller: 23
        channel: 0

      - sequence: s
        label: volume -
        type: analog
        increment: -1
        controller: 23
        channel: 0

  - id: track 8
    mappings:
      - sequence: z
        label: volume +
        type: analog
        increment: 1
        controller: 24
        channel: 0

      - sequence: s
        label: volume -
        type: analog
        increment: -1
        controller: 24
        channel: 0

  - id: encoder 1
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 1
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 1
        channel: 0

  - id: encoder 2
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 2
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 2
        channel: 0

  - id: encoder 3
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 3
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 3
        channel: 0

  - id: encoder 4
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 4
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 4
        channel: 0

  - id: encoder 5
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 5
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 5
        channel: 0

  - id: encoder 6
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 6
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 6
        channel: 0

  - id: encoder 7
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 7
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 7
        channel: 0

  - id: encoder 8
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 8
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 8
        channel: 0

  - id: encoder 9
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 9
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 9
        channel: 0

  - id: encoder 10
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 10
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 10
        channel: 0

  - id: encoder 11
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 11
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 11
        channel: 0

  - id: encoder 12
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 12
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 12
        channel: 0

  - id: encoder 13
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 13
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 13
        channel: 0

  - id: encoder 14
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 14
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 14
        channel: 0

  - id: encoder 15
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 15
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 15
        channel: 0

  - id: encoder 16
    mappings:
      - sequence: z
        label: encoder +
        type: analog
        increment: 1
        controller: 16
        channel: 0

      - sequence: s
        label: encoder -
        type: analog
        increment: -1
        controller: 16
        channel: 0
